name: Terraform Infrastructure Deployment

on:
  workflow_dispatch:

env:
  WORKING_DIR: ./Environments

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Init, Validate & Plan

    # Self-hosted Runner
    runs-on:
      - self-hosted
      # Agar custom labels hain to unhe bhi add karo
      # - linux
      # - x64

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file="UAT.terraform.tfvars" \
            -input=false \
            -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.WORKING_DIR }}/tfplan